# Until https://review.openstack.org/608453 merges, we need to add
# Gerrit's SSH host keys to the known hosts_file before starting.

- hosts: localhost
  gather_facts: false
  tasks:
    - name: Wait for gerrit to start
      wait_for:
        host: gerrit
        port: 29418
    - name: Ensure SSH directory exists
      file:
        state: directory
        path: /root/.ssh
    - name: Fetch SSH host keys from Gerrit
      shell: ssh-keyscan -p 29418 gerrit > /root/.ssh/known_hosts
